### ISSUE TITLE
8.0.0-beta.1 doesn't include liferay-theme-deps-6.2

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-themes-sdk#38]
You can't use the latest version of the Upgrade task to upgrade and 6.2 theme to 7.0 and 7.1. It needs to include support for liferay-theme-deps-6.2.

**Comment by jbalsas** [comment]
Hey @mwilliams2014 , why is that needed? Since you're simply upgrading and not building for `6.2`, I'd expect those shouldn't be needed... 🤔 

Could you add `Steps to Reproduce`, `Expected behaviour` and `Curent behaviour` describing the problem you observed so we can reproduce on our side?

Thanks!

**Comment by mwilliams2014** [comment]
@jbalsas, perhaps I worded it wrong. What I mean to say is that you can't upgrade a 6.2 theme using the latest version of the Liferay Themes Node.js SDK version 8.0.0-beta.1. You must first upgrade it to 7.0 with its current liferay-theme-deps and liferay-theme-tasks versions, then you must manually change those dependencies to version 8.0.0-beta.1 to upgrade from 7.0 to 7.1. Why can't we use the latest version from the start to upgrade a 6.2 theme?
