### ISSUE TITLE
Generator-Liferay-Theme: Do not insist on app server directory

### ISSUE THREAD

**Issue by sbaechler** [liferay/liferay-themes-sdk#67]
During the liferay-theme generator process the user has to enter the path to the app server directory. The assistant would not continue if the path was not valid.

We are running Liferay from a Docker container and not a local Tomcat instance and therefore there is no app server directory.

Please allow the assistant to finish if there is no such directory. Of course the default live reload tasks are not going to work.
Maybe add https://github.com/GlassOfWhiskey/docker-gulp-tasks-4-liferay to core.

**Comment by jbalsas** [comment]
Hey @sbaechler, thanks for reporting this!

I'll treat this as a bug, and I've filed https://github.com/liferay/liferay-themes-sdk/issues/72 to look into supporting Docker. Feel free to contribute with a PR!! 😉

**Comment by GlassOfWhiskey** [comment]
Hi @sbaechler,
could you please describe in more detail the structure of your Dev environment? The part of the issue that that I can't understand is: "therefore there is no app server directory".
I understand that you are using a Docker container to run Liferay, but didn't you create bind mounts with folders on your file system? Do you expect to deploy the theme war directly inside your container, perhaps with a 'docker cp' command? As far as I can see, this solution has a drawback: if you stop and restart your container, you have to deploy again your modules/themes/lpkgs and so on.
Instead, with bind mounts deployed files are automatically synchronized with the container file system, but they are persisted on your local file system so you can deploy only when you need to do that. But in this case you actually have an app server directory: the same that you would use with a standard Liferay Workspace environment.

**Comment by GlassOfWhiskey** [comment]
Hi @sbaechler and @jbalsas,
I decided to support the absence of bind mounts for theme deployment.
I think that you could use the same container for production and local development by simply adding or removing bind mounts from the launch command (o from docker-compose file if you use one).
Nevertheless, I like the fact that, if bind mounts are not necessary, a frontend developer doesn't need to download the entire Liferay workspace on his machine to replicate the environment, but he has only to pull a container from somewhere and he can start developing themes.
In such a scenario, you have to insert the path to your Liferay server INSIDE your container. The deployment operation will then copy your .war file from the distFolder on your host machine to the appServerPath inside your container, using a sort of docker cp command.
However, please pay attention to the fact that, in order to support watch task, you have to allow GoGo shell requests from a remote host (in particular because your host machine needs to connect to your container with a watch socket), but this is not recommended on production environments.
