### ISSUE TITLE
Minor typo in prompt

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-themes-sdk#76]
Please close this issue if this is not an intended use case

1. Create new theme (Ex: My New Theme)
2. Run generator again and create theme with the same name.
3. You are prompted if you want to overwrite the existing package.json, but the message contains extra characters `ynaxdH` should just be `y`.

 conflict package.json
? Overwrite package.json? (ynaxdH)

**Comment by jbalsas** [comment]
Hey @mwilliams2014, this is the default [conflict resolution from Yeoman]( http://yeoman.io/generator/Conflicter.html). The default options mean:
```
Y Yes, overwrite
n No, do not overwrite
a All, overwrite this and all others
x Exit, abort
d Diff, show the differences between the old and the new
h Help, show this help
```

I also think that this is a bit confusing, since the starting point is that you're basically walking all over an existing theme. Maybe a better solution would be to warn beforehand and halt the whole process at once?

**Comment by mwilliams2014** [comment]
Oh @jbalsas, I didn't know that :-) I think you're right though, a warning beforehand that halts the whole process would probably be best.

**Comment by jbalsas** [comment]
I've been reading through this, and this is actually the expectation from Yeoman generators. People expect to be able to re-run the generator and have things updated.

I'm closing this for now. We can always rethink this if people often get confused by it.

**Comment by mwilliams2014** [comment]
Ok. Sounds good
